# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[menu]]
  name = "Grants"
  url = "#grants"
  weight = 40

[[menu]]
  name = "Teaching"
  url = "#teaching"
  weight = 50

[[menu]]
  name = "Training"
  url = "#training"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[menu]]
  name = "CV"
  weight = 80
  hasChildren = true
  
[[menu]]
  name = "CV Short"
  parent = "CV"
  url = "files/cv/CVshort.pdf"
  target="_blank"
  
[[menu]]
  name = "CV Long"
  parent = "CV"
  url = "files/cv/CVgithub.pdf"
  target="_blank"
